import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { Photo, SectionIntro } from "@/components/UI";
import { siteConfig } from "@/content/site";
export const metadata: Metadata={title:"东梵青抹",description:"东梵青抹 DONGFAN MATCHA — by WEICANG。从一片梵净山抹茶园开始的年度关系。",alternates:{canonical:"/dongfan-matcha"}};
export default function Dongfan(){const lines=[["A","梵净山原产地课堂","¥69,800 / 人","企业家 / Founder / CEO / EMBA"],["B","青山青年","¥5,980 / 人 / 年","青年创业者 / Creator / 贵州青年 / IP"],["C","企业年度认养礼","¥3,980 / 份 / 年","员工 / 客户 / 高管 / 企业福利"]];return <div className="dongfan-page"><section className="dongfan-hero"><Image src="/assets/photos/tea-hands.jpg" alt="梵净山茶园中的采茶双手" fill priority sizes="100vw"/><div><Image src="/assets/brand/dongfan-matcha-logo.png" alt="东梵青抹" width={1400} height={500}/><p>DONGFAN MATCHA — by WEICANG</p><h1 className="serif">一片茶园。四个季节。<br />一段可以回去的关系。</h1></div></section>
<section className="origin"><SectionIntro index="01" label="ORIGIN" title="从梵净山开始。"/><Photo src="/assets/photos/fanjing-mountain.jpg" alt="云海中的梵净山" className="origin-photo"/><div className="origin-copy"><p className="origin-lede">山、茶园、四季与东方茶生活。原产地不是背景，而是每一年关系真正开始与返回的地方。</p><div className="origin-notes"><span><small>01</small><b>山</b><em>MOUNTAIN</em></span><span><small>02</small><b>茶园</b><em>TEA GARDEN</em></span><span><small>03</small><b>四季</b><em>FOUR SEASONS</em></span></div><p className="origin-signoff">ROOTED IN FANJING MOUNTAIN<br/>GUIZHOU, CHINA</p></div></section>
<section className="adoption"><p className="eyebrow">02 / ADOPTION</p><h2 className="serif">认养不是交易，<br />是一段年度关系。</h2><div className="not-is"><div><b>IT IS NOT</b><p>不是买地 · 土地所有权 · 投资 · 金融产品 · 一次旅行</p></div><div><b>IT IS</b><p>一片真实茶园 · 园主身份 · 一整年产品 · 内容 · 原产地体验 · 回到山里的理由</p></div></div><p className="legal-note">认养为年度产品、会员、内容与体验服务，不涉及土地产权、投资收益或金融回报。</p></section>
<section className="three-lines"><SectionIntro index="03" label="THREE LINES" title="三种进入年度关系的方式。"/><div>{lines.map(x=><article key={x[0]}><small>{x[0]} LINE</small><h3>{x[1]}</h3><strong>{x[2]}</strong><p>{x[3]}</p></article>)}</div><p>具体权益与最终方案以正式发布为准。</p></section>
<section className="seasons"><SectionIntro index="04" label="FOUR SEASONS" title="不是一盒礼，是一整年的生活方式。"/><div>{[["春","第一抹新绿"],["夏","山里冰抹"],["秋","抹茶时刻"],["冬","一席抹茶"]].map((x,i)=><span key={x[0]}><small>0{i+1}</small><b>{x[0]}</b><em>{x[1]}</em></span>)}</div></section>
<section className="passport"><div><p className="eyebrow">05 / GARDEN PASSPORT</p><h2>东梵园籍</h2><p className="serif">一段关系，需要一个身份。</p></div><div>{["园号","年份","茶园","产品","权益","活动","年度报告"].map(x=><span key={x}>{x}</span>)}<p>AI 在后台，关系站到前台。</p></div></section>
<section className="characters"><p className="eyebrow">06 / CHARACTER IP</p><h2>Momo & Nuonuo</h2><p>抹抹与糯糯是东梵青抹旗下 Character IP，服务于主品牌、会员、内容与社群，不作为平级品牌入口。</p></section>
<section className="dongfan-external"><p>DONGFAN MATCHA — by WEICANG</p><h2 className="serif">从山的一年，开始一段关系。</h2><Link className="button button--dark" href={siteConfig.dongfanUrl}>Visit DONGFAN MATCHA ↗</Link></section></div>}
